# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - internal-net
    env_file: .env
    depends_on:
      localstack:
        condition: service_started
      opensearch:
        condition: service_started
        restart: true

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./localstack:/etc/localstack/init/ready.d
    networks:
      - internal-net

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - internal-net
    restart: always
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - plugins.security.restapi.password_score_based_validation_strength=fair
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD="oJjHYJinNQ2k4!iQWTxrPdsmbtWA*4"

networks:
  internal-net:
    name: internal-vector-search