services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - IS_LOCAL=${IS_LOCAL}
      - LOG_LEVEL=${LOG_LEVEL}
      - OPENSEARCH_INDEX=${OPENSEARCH_INDEX}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - OPENSEARCH_USER=${OPENSEARCH_USER}
      - OPENSEARCH_PASS=${OPENSEARCH_PASS}
      - OPENSEARCH_USE_SSL=${OPENSEARCH_USE_SSL}
      - OPENSEARCH_VERIFY_CERTS=${OPENSEARCH_VERIFY_CERTS}
      - S3_URL=${S3_URL}
      - HF_HOME=/tmp/
    networks:
      my_network:
        aliases:
          - server_backend
networks:
  my_network:
    name: my_network